apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: java-springboot-basic-monitor
  name: java-springboot-basic-monitor
spec:
  endpoints:
  - interval: 10s
    path: /actuator/prometheus
    port: http-8081
    scheme: http
  selector:
    matchLabels:
      app: java-springboot-basic
